
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daorpdnaganfugudqkmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhb3JwZG5hZ2FuZnVndWRxa21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzcxODgsImV4cCI6MjA2MDQxMzE4OH0.op3xLPd8TLjqozzI21xZxNFrDqXO9uVyKZzY6-8cpSc";

console.log(`[${new Date().toISOString()}] Initializing Supabase client with URL:`, SUPABASE_URL);

// Anonymous client - USE THIS FOR PUBLIC ACCESS
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Changed to true for better session handling
    autoRefreshToken: true, // Changed to true to auto-refresh tokens
  },
  global: {
    // Adding fetch options to debug
    fetch: (url, options) => {
      // Log fetch requests for debugging
      console.log(`[${new Date().toISOString()}] Supabase fetch request:`, { 
        url: url.toString(), 
        method: options?.method,
      });
      
      // Set appropriate headers for cross-origin requests and API key
      const headers = options?.headers || {};
      options = {
        ...options,
        headers: {
          ...headers,
          'Content-Type': 'application/json',
          'apikey': SUPABASE_PUBLISHABLE_KEY, // Explicitly add the API key to headers
        },
        cache: 'no-cache', // Disable caching to avoid stale data
      };
      
      return fetch(url, options);
    },
  },
});

// Add initialization success check
supabase.from('contacts')
  .select('id')
  .limit(1)
  .then(({ data, error }) => {
    if (error) {
      console.error(`[${new Date().toISOString()}] Supabase initialization test failed:`, error);
    } else {
      console.log(`[${new Date().toISOString()}] Supabase initialization successful - contacts table accessible`);
    }
  });

// Test insert permissions (for debugging)
const testInsertPermissions = async () => {
  console.log(`[${new Date().toISOString()}] Testing insert permissions on contacts table...`);
  try {
    // This is just a test that won't actually insert data
    // Using a select query instead of an insert to avoid adding test data
    const { error } = await supabase
      .from('contacts')
      .select('id')
      .limit(1);
      
    if (error) {
      console.error(`[${new Date().toISOString()}] Permission test error:`, error);
    } else {
      console.log(`[${new Date().toISOString()}] Permission test successful`);
    }
  } catch (error) {
    console.error(`[${new Date().toISOString()}] Error testing permissions:`, error);
  }
};

// Run the permissions test to verify connection
testInsertPermissions();
